rm(list=ls())
library("biomaRt")
mart= useMart(biomart="ensembl", dataset="hsapiens_gene_ensembl")
setwd("/Users/swati/Desktop/Biomart-extraction-Go-terms/calculate-second-degree-neighbors")
restgenelist= read.table("rest-genes-ensembl-id", header=TRUE)
#data=getBM(attributes = c('hgnc_symbol',"go_id","name_1006","definition_1006","go_linkage_type","namespace_1003"), values=genelist, mart=mart, filters="hgnc_symbol",uniqueRows = TRUE)
data=getBM(attributes = c('hgnc_symbol',"ensembl_gene_id","go_id","name_1006","definition_1006","go_linkage_type","namespace_1003"), values=restgenelist, mart=mart, filters="ensembl_gene_id",uniqueRows = TRUE)
#data=getBM(attributes = c('hgnc_symbol',"ensembl_gene_id"), values=genelist, mart=mart, filters="hgnc_symbol",uniqueRows = TRUE)
write.table(data, file="Biomart-downloaded.second-neighbors-set2.txt", sep="\t")
